[[language]]
name = "grammar"
scope = "source.grammar"
injection-regex = "grammar"
file-types = ["grammar"]
comment-tokens = "//"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "grammar" , args = ["fmt"] }
language-servers = [ "grammar" ]

[language-server.grammar]
command = "grammar"
args = ["lsp"]
config = { provideFormatter = true }
# environment = { "ENV1" = "value1", "ENV2" = "value2" }
